"""add preferred_theme to users

Revision ID: 3f71d342a7c0
Revises: c351be147975
Create Date: 2026-05-27 17:34:16.705734

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3f71d342a7c0'
down_revision: Union[str, Sequence[str], None] = 'c351be147975'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('preferred_theme', sa.String(length=10), nullable=False, server_default='system'))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'preferred_theme')
    # ### end Alembic commands ###
